InvoiceProjectinMVC/Controllers/AddController.cs
using InvoiceProjectinMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InvoiceProjectinMVC.Controllers
{
    public class AddController : Controller
    {
        invoicelistanddetailsEntities db = new invoicelistanddetailsEntities();
        // GET: Add
        public ActionResult Index()
        {
            var data = db.Invoice_List.ToList();
            return View(data);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Invoice_List l)
        {
            if (ModelState.IsValid == true)
            {
                db.Invoice_List.Add(l);
                int a = db.SaveChanges();
                if (a > 0)
                {
                    TempData["InsertMsg"] = "<script>alert('Inserted')</script>";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["InsertMsg"] = "<script>alert('Not Inserted')</script>";
                }
            }
            return View();
        }
        public ActionResult Edit(int id)
        {

            var row = db.Invoice_List.Where(model => model.Invoice_id == id).FirstOrDefault();
            return View(row);
        }
        [HttpPost]
        public ActionResult Edit(Invoice_List i)
        {
            if (ModelState.IsValid == true)
            {
                db.Entry(i).State = System.Data.Entity.EntityState.Modified;
                int a = db.SaveChanges();
                if (a > 0)
                {
                    TempData["UpdateMsg"] = "<script>alert('Updated')</script>";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["UpdateMsg"] = "<script>alert('Not Updated')</script>";
                }
            }
            return View();
        }
        public ActionResult Delete(int id)
        {
            var row = db.Invoice_List.Find(id);
            return View(row);
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Invoice_List data = db.Invoice_List.Find(id);
            db.Invoice_List.Remove(data);
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        
        public ActionResult CreateForm()
        {
            var list = new List<string>() { "Mahesh", "Ramesh", "Suresh" };
            ViewBag.list = list;
            var list1 = new List<string>() { "Paid", "Sent", "Draft" };
            ViewBag.list1 = list1;
            var list2 = new List<string>() { "Product1", "Product2", "Product3" };
            ViewBag.list2 = list2;
            return View();

        }
        [HttpPost]
        public ActionResult CreateForm(ViewModel v)
        {
            var list = new List<string>() { "Mahesh", "Ramesh", "Suresh" };
            ViewBag.list = list;
            var list1 = new List<string>() { "Paid", "Sent", "Draft" };
            ViewBag.list1 = list1;
            var list2 = new List<string>() { "Product1", "Product2", "Product3" };
            ViewBag.list2 = list2;
           

            if (ModelState.IsValid == true)
            {
                db.Invoice_List.Add(v.model1);

                db.Invoice_Details.Add(v.model2);
                
              //  db.Invoice_Details.Add(v.model2);
                int a = db.SaveChanges();
                if (a > 0)
                {
                    TempData["InsertMsg"] = "<script>alert('Inserted')</script>";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["InsertMsg"] = "<script>alert('Not Inserted')</script>";
                }
            }
            return View();
        }
    }
}

InvoiceProjectinMVC/Views/Add/Create.cshtml
@model InvoiceProjectinMVC.Models.Invoice_List

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Invoice_List</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Invoice_No, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Invoice_No, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Invoice_No, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bill_To, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bill_To, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bill_To, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Invoice_Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Invoice_Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Invoice_Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Due_Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Due_Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Due_Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InvoiceProjectinMVC/Views/Add/Delete.cshtml
@model InvoiceProjectinMVC.Models.Invoice_List

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Invoice_List</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Invoice_No)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Invoice_No)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bill_To)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bill_To)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Invoice_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Invoice_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Due_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Due_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

InvoiceProjectinMVC/Views/Add/Edit.cshtml
@model InvoiceProjectinMVC.Models.Invoice_List

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Invoice_List</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Invoice_id)

        <div class="form-group">
            @Html.LabelFor(model => model.Invoice_No, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Invoice_No, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Invoice_No, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bill_To, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bill_To, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bill_To, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Invoice_Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Invoice_Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Invoice_Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Due_Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Due_Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Due_Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InvoiceProjectinMVC/Views/Add/Index.cshtml
@model IEnumerable<InvoiceProjectinMVC.Models.Invoice_List>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@Html.Raw(TempData["InsertMsg"])
@Html.Raw(TempData["UpdateMsg"])

<p>
    @Html.ActionLink("Create New", "CreateForm")
    @*<div class="form-group">
        <input type="button" value="Create" class="add btn btn-primary" onclick="location.href=windows('@Url.Action("CreateForm", "Add")')" />
    </div>*@


</p>
<table class="table table-bordered" id="MyTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Invoice_No)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bill_To)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Invoice_Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Due_Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Invoice_No)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Bill_To)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Invoice_Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Due_Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Invoice_id }) |
                    @*@Html.ActionLink("Details", "Details", new { id = item.Invoice_id }) |*@
                    @Html.ActionLink("Delete", "Delete", new { id = item.Invoice_id })
                </td>
            </tr>
        }
    </tbody>
</table>